package com.example.buyorders.manager;

import com.example.buyorders.BuyOrders;
import com.example.buyorders.model.BuyOrder;
import com.example.buyorders.util.ItemMatcher;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.util.io.BukkitObjectInputStream;
import org.bukkit.util.io.BukkitObjectOutputStream;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.stream.Collectors;

public class OrderManager {

    public record FillResult(String error, List<ItemStack> rejectedItems) {
        public static FillResult error(String error, List<ItemStack> rejectedItems) {
            return new FillResult(error, rejectedItems == null ? List.of() : rejectedItems);
        }

        public static FillResult success(List<ItemStack> rejectedItems) {
            return new FillResult(null, rejectedItems == null ? List.of() : rejectedItems);
        }
    }

    private final BuyOrders plugin;
    private final File legacyDataFile;
    private final File databaseFile;
    private Connection connection;

    private final Map<UUID, BuyOrder> orders = new LinkedHashMap<>();
    private final Map<UUID, List<ItemStack>> pendingDeliveries = new HashMap<>();

    public OrderManager(BuyOrders plugin) {
        this.plugin = plugin;
        this.legacyDataFile = new File(plugin.getDataFolder(), "orders.yml");
        this.databaseFile = new File(plugin.getDataFolder(), "orders");
    }

    public synchronized void load() {
        orders.clear();
        pendingDeliveries.clear();

        try {
            initDatabase();
            loadFromDatabase();

            if (!isLegacyYamlMigrated() && legacyDataFile.exists() && isDatabaseEmpty()) {
                loadFromLegacyYaml();
                if (save()) {
                    setMetadata("legacy_yaml_migrated", "true");
                    plugin.getLogger().info("Migrated orders.yml into H2 database.");
                }
            }
        } catch (SQLException ex) {
            plugin.getLogger().log(Level.SEVERE, "Failed loading orders database", ex);
        }
    }

    private void initDatabase() throws SQLException {
        File parent = databaseFile.getParentFile();
        if (parent != null && !parent.exists()) parent.mkdirs();

        if (connection != null && !connection.isClosed()) return;

        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException ex) {
            throw new SQLException("H2 driver is not available. Build with Maven shading or let Paper load plugin libraries.", ex);
        }

        String url = "jdbc:h2:" + databaseFile.getAbsolutePath().replace("\\", "/") + ";DATABASE_TO_UPPER=false";
        connection = DriverManager.getConnection(url);

        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS orders (
                        id VARCHAR(36) PRIMARY KEY,
                        buyer_uuid VARCHAR(36) NOT NULL,
                        buyer_name VARCHAR(64) NOT NULL,
                        material VARCHAR(64) NOT NULL,
                        item_template BLOB NOT NULL,
                        quantity_wanted INT NOT NULL,
                        quantity_filled INT NOT NULL,
                        price_each DOUBLE NOT NULL,
                        created_at BIGINT NOT NULL
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS pending_deliveries (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        player_uuid VARCHAR(36) NOT NULL,
                        sort_order INT NOT NULL,
                        item_stack BLOB NOT NULL
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS metadata (
                        meta_key VARCHAR(64) PRIMARY KEY,
                        meta_value VARCHAR(255) NOT NULL
                    )
                    """);
        }
    }

    private void loadFromDatabase() throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT id, buyer_uuid, buyer_name, item_template, quantity_wanted, quantity_filled, price_each, created_at
                FROM orders
                ORDER BY created_at ASC
                """);
             ResultSet result = statement.executeQuery()) {
            while (result.next()) {
                try {
                    UUID id = UUID.fromString(result.getString("id"));
                    UUID buyerUuid = UUID.fromString(result.getString("buyer_uuid"));
                    String buyerName = result.getString("buyer_name");
                    ItemStack template = deserializeItem(result.getBytes("item_template"));
                    template.setAmount(1);
                    int wanted = result.getInt("quantity_wanted");
                    int filled = result.getInt("quantity_filled");
                    double price = result.getDouble("price_each");
                    long created = result.getLong("created_at");

                    orders.put(id, new BuyOrder(id, buyerUuid, buyerName, template, wanted, filled, price, created));
                } catch (Exception ex) {
                    plugin.getLogger().log(Level.WARNING, "Failed to load order row", ex);
                }
            }
        }

        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT player_uuid, item_stack
                FROM pending_deliveries
                ORDER BY player_uuid ASC, sort_order ASC, id ASC
                """);
             ResultSet result = statement.executeQuery()) {
            while (result.next()) {
                try {
                    UUID uuid = UUID.fromString(result.getString("player_uuid"));
                    ItemStack item = deserializeItem(result.getBytes("item_stack"));
                    pendingDeliveries.computeIfAbsent(uuid, ignored -> new ArrayList<>()).add(item);
                } catch (Exception ex) {
                    plugin.getLogger().log(Level.WARNING, "Failed to load pending delivery row", ex);
                }
            }
        }
    }

    private boolean isDatabaseEmpty() throws SQLException {
        return countRows("orders") == 0 && countRows("pending_deliveries") == 0;
    }

    private int countRows(String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM " + table)) {
            result.next();
            return result.getInt(1);
        }
    }

    private boolean isLegacyYamlMigrated() throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT meta_value FROM metadata WHERE meta_key = ?")) {
            statement.setString(1, "legacy_yaml_migrated");
            try (ResultSet result = statement.executeQuery()) {
                return result.next() && Boolean.parseBoolean(result.getString("meta_value"));
            }
        }
    }

    private void setMetadata(String key, String value) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                MERGE INTO metadata (meta_key, meta_value) KEY(meta_key) VALUES (?, ?)
                """)) {
            statement.setString(1, key);
            statement.setString(2, value);
            statement.executeUpdate();
        }
    }

    private void loadFromLegacyYaml() {
        YamlConfiguration config = YamlConfiguration.loadConfiguration(legacyDataFile);

        if (config.isConfigurationSection("orders")) {
            for (String key : config.getConfigurationSection("orders").getKeys(false)) {
                try {
                    String path = "orders." + key + ".";

                    UUID id = UUID.fromString(config.getString(path + "id"));
                    UUID buyerUuid = UUID.fromString(config.getString(path + "buyer-uuid"));
                    String buyerName = config.getString(path + "buyer-name", "Unknown");

                    ItemStack template = config.getItemStack(path + "item-template");
                    if (template == null) {
                        Material mat = Material.valueOf(config.getString(path + "material"));
                        template = new ItemStack(mat);
                    }

                    restoreItem(config, path + "item-data.", template);
                    template.setAmount(1);

                    int wanted = config.getInt(path + "quantity-wanted");
                    int filled = config.getInt(path + "quantity-filled");
                    double price = config.getDouble(path + "price-each");
                    long created = config.getLong(path + "created-at");

                    orders.put(id, new BuyOrder(id, buyerUuid, buyerName, template, wanted, filled, price, created));
                } catch (Exception ex) {
                    plugin.getLogger().log(Level.WARNING, "Failed to load order " + key, ex);
                }
            }
        }

        if (config.isConfigurationSection("pending")) {
            for (String key : config.getConfigurationSection("pending").getKeys(false)) {
                try {
                    UUID uuid = UUID.fromString(key);
                    List<ItemStack> items = loadPendingItems(config, "pending." + key);

                    if (!items.isEmpty()) {
                        pendingDeliveries.put(uuid, items);
                    }
                } catch (Exception ex) {
                    plugin.getLogger().log(Level.WARNING, "Failed to load pending " + key, ex);
                }
            }
        }
    }

    public synchronized boolean save() {
        try {
            initDatabase();
            boolean previousAutoCommit = connection.getAutoCommit();
            connection.setAutoCommit(false);

            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("DELETE FROM pending_deliveries");
                statement.executeUpdate("DELETE FROM orders");
            }

            try (PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO orders (
                        id, buyer_uuid, buyer_name, material, item_template, quantity_wanted,
                        quantity_filled, price_each, created_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """)) {
                for (BuyOrder order : orders.values()) {
                    statement.setString(1, order.getId().toString());
                    statement.setString(2, order.getBuyerUuid().toString());
                    statement.setString(3, order.getBuyerName());
                    statement.setString(4, order.getMaterial().name());
                    statement.setBytes(5, serializeItem(order.getItemTemplate()));
                    statement.setInt(6, order.getQuantityWanted());
                    statement.setInt(7, order.getQuantityFilled());
                    statement.setDouble(8, order.getPriceEach());
                    statement.setLong(9, order.getCreatedAt());
                    statement.addBatch();
                }
                statement.executeBatch();
            }

            try (PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO pending_deliveries (player_uuid, sort_order, item_stack)
                    VALUES (?, ?, ?)
                    """)) {
                for (Map.Entry<UUID, List<ItemStack>> entry : pendingDeliveries.entrySet()) {
                    int index = 0;
                    for (ItemStack item : entry.getValue()) {
                        if (item == null || item.getType().isAir()) continue;

                        statement.setString(1, entry.getKey().toString());
                        statement.setInt(2, index++);
                        statement.setBytes(3, serializeItem(item));
                        statement.addBatch();
                    }
                }
                statement.executeBatch();
            }

            connection.commit();
            connection.setAutoCommit(previousAutoCommit);
            return true;
        } catch (Exception ex) {
            rollbackQuietly();
            plugin.getLogger().log(Level.SEVERE, "Failed saving orders database", ex);
            return false;
        }
    }

    private void rollbackQuietly() {
        if (connection == null) return;
        try {
            connection.rollback();
            connection.setAutoCommit(true);
        } catch (SQLException ignored) {
        }
    }

    public synchronized void close() {
        if (connection == null) return;
        try {
            connection.close();
        } catch (SQLException ex) {
            plugin.getLogger().log(Level.WARNING, "Failed closing orders database", ex);
        } finally {
            connection = null;
        }
    }

    private byte[] serializeItem(ItemStack item) throws IOException {
        try (ByteArrayOutputStream bytes = new ByteArrayOutputStream();
             BukkitObjectOutputStream output = new BukkitObjectOutputStream(bytes)) {
            output.writeObject(item);
            return bytes.toByteArray();
        }
    }

    private ItemStack deserializeItem(byte[] bytes) throws IOException, ClassNotFoundException {
        try (ByteArrayInputStream inputBytes = new ByteArrayInputStream(bytes);
             BukkitObjectInputStream input = new BukkitObjectInputStream(inputBytes)) {
            return (ItemStack) input.readObject();
        }
    }

    public synchronized boolean addOrder(BuyOrder order) {
        orders.put(order.getId(), order);
        if (save()) return true;

        orders.remove(order.getId());
        return false;
    }

    public synchronized List<BuyOrder> getOrders() {
        return orders.values().stream()
                .filter(o -> !o.isFulfilled())
                .sorted(Comparator.comparingDouble(BuyOrder::getPriceEach).reversed())
                .collect(Collectors.toList());
    }

    public synchronized List<BuyOrder> getOrdersByPlayer(UUID playerUuid) {
        return orders.values().stream()
                .filter(o -> !o.isFulfilled())
                .filter(o -> o.getBuyerUuid().equals(playerUuid))
                .collect(Collectors.toList());
    }

    public synchronized List<BuyOrder> getOrdersByMaterial(Material material) {
        return orders.values().stream()
                .filter(o -> !o.isFulfilled())
                .filter(o -> o.getMaterial() == material)
                .collect(Collectors.toList());
    }

    public synchronized BuyOrder getOrder(UUID id) {
        return orders.get(id);
    }

    public String cancelOrder(Player player, UUID orderId) {
        BuyOrder order;

        synchronized (this) {
            order = orders.get(orderId);

            if (order == null) return plugin.msg("order-not-found");

            if (!order.getBuyerUuid().equals(player.getUniqueId())
                    && !player.hasPermission("axorders.admin")) {
                return plugin.msg("no-permission");
            }

            orders.remove(orderId);
            if (!save()) {
                orders.put(order.getId(), order);
                save();
                return plugin.msg("order-save-failed");
            }
        }

        boolean refunded = plugin.getCurrencyManager()
                .give(order.getBuyerUuid(), order.getRemaining() * order.getPriceEach());

        if (!refunded) {
            synchronized (this) {
                orders.put(order.getId(), order);
                save();
            }
            return plugin.msg("refund-failed");
        }

        return null;
    }

    public String fillOrder(Player seller, UUID orderId) {
        return fillOrder(seller, orderId, Integer.MAX_VALUE);
    }

    public String fillOrder(Player seller, UUID orderId, int requestedAmount) {
        if (requestedAmount <= 0) return plugin.msg("invalid-amount");

        BuyOrder order;

        synchronized (this) {
            order = orders.get(orderId);

            if (order == null) return plugin.msg("order-not-found");

            if (order.getBuyerUuid().equals(seller.getUniqueId()))
                return plugin.msg("own-order");

            if (order.isFulfilled())
                return plugin.msg("order-not-found");
        }

        int available = countItems(seller, order.getItemTemplate());
        if (available <= 0)
            return plugin.msg("no-items", "{material}", itemName(order.getItemTemplate()));

        int amount = Math.min(requestedAmount, Math.min(available, order.getRemaining()));
        if (amount <= 0)
            return plugin.msg("no-items");

        double payment = amount * order.getPriceEach();

        List<ItemStack> toRemove = new ArrayList<>();
        int left = amount;

        for (ItemStack item : seller.getInventory().getContents()) {
            if (item == null || left <= 0) continue;
            if (!ItemMatcher.matchesCustomItem(item, order.getItemTemplate())) continue;

            int take = Math.min(item.getAmount(), left);

            ItemStack copy = item.clone();
            copy.setAmount(take);
            toRemove.add(copy);

            left -= take;
        }

        boolean paid = plugin.getCurrencyManager()
                .give(seller.getUniqueId(), payment);

        if (!paid) return plugin.msg("no-currency-hook");

        int remaining = amount;

        for (int i = 0; i < seller.getInventory().getSize() && remaining > 0; i++) {
            ItemStack item = seller.getInventory().getItem(i);
            if (item == null) continue;
            if (!ItemMatcher.matchesCustomItem(item, order.getItemTemplate())) continue;

            int take = Math.min(item.getAmount(), remaining);

            if (item.getAmount() <= take) {
                seller.getInventory().setItem(i, null);
            } else {
                item.setAmount(item.getAmount() - take);
            }

            remaining -= take;
        }

        synchronized (this) {
            BuyOrder current = orders.get(orderId);

            if (current == null) {
                seller.getInventory().addItem(toRemove.toArray(ItemStack[]::new));
                plugin.getCurrencyManager().take(seller.getUniqueId(), payment);
                return plugin.msg("order-not-found");
            }

            int previousFilled = current.getQuantityFilled();
            current.setQuantityFilled(current.getQuantityFilled() + amount);

            boolean removedFulfilled = false;
            if (current.isFulfilled()) {
                orders.remove(orderId);
                removedFulfilled = true;
            }

            List<ItemStack> buyerPending = pendingDeliveries.computeIfAbsent(current.getBuyerUuid(), k -> new ArrayList<>());
            buyerPending.addAll(toRemove);

            if (!save()) {
                removeLastAdded(buyerPending, toRemove.size());
                if (buyerPending.isEmpty()) pendingDeliveries.remove(current.getBuyerUuid());

                current.setQuantityFilled(previousFilled);
                if (removedFulfilled) orders.put(orderId, current);

                seller.getInventory().addItem(toRemove.toArray(ItemStack[]::new));
                boolean refunded = plugin.getCurrencyManager().take(seller.getUniqueId(), payment);
                save();
                return plugin.msg(refunded ? "order-save-failed" : "refund-failed");
            }
        }

        seller.sendMessage(plugin.msg("order-filled",
                "{amount}", String.valueOf(amount),
                "{material}", itemName(order.getItemTemplate()),
                "{payment}", plugin.getCurrencyManager().format(payment)));

        return null;
    }

    public FillResult fillOrder(Player seller, UUID orderId, List<ItemStack> offeredItems) {
        List<ItemStack> offered = cloneItems(offeredItems);

        BuyOrder order;
        int remainingWanted;

        synchronized (this) {
            order = orders.get(orderId);

            if (order == null) return FillResult.error(plugin.msg("order-not-found"), offered);

            if (order.getBuyerUuid().equals(seller.getUniqueId()))
                return FillResult.error(plugin.msg("own-order"), offered);

            if (order.isFulfilled())
                return FillResult.error(plugin.msg("order-not-found"), offered);

            remainingWanted = order.getRemaining();
        }

        if (offered.isEmpty()) {
            return FillResult.error(plugin.msg("no-items", "{material}", itemName(order.getItemTemplate())), List.of());
        }

        List<ItemStack> accepted = new ArrayList<>();
        List<ItemStack> rejected = new ArrayList<>();
        int acceptedAmount = splitAcceptedItems(offered, order.getItemTemplate(), remainingWanted, accepted, rejected);

        if (acceptedAmount <= 0) {
            return FillResult.error(plugin.msg("no-items", "{material}", itemName(order.getItemTemplate())), rejected);
        }

        double payment = acceptedAmount * order.getPriceEach();
        boolean paid = plugin.getCurrencyManager().give(seller.getUniqueId(), payment);
        if (!paid) return FillResult.error(plugin.msg("no-currency-hook"), offered);

        synchronized (this) {
            BuyOrder current = orders.get(orderId);

            if (current == null || current.isFulfilled()) {
                plugin.getCurrencyManager().take(seller.getUniqueId(), payment);
                return FillResult.error(plugin.msg("order-not-found"), offered);
            }

            if (acceptedAmount > current.getRemaining()) {
                List<ItemStack> trimmedAccepted = new ArrayList<>();
                List<ItemStack> trimmedRejected = new ArrayList<>(rejected);
                int trimmedAmount = splitAcceptedItems(accepted, current.getItemTemplate(), current.getRemaining(), trimmedAccepted, trimmedRejected);

                plugin.getCurrencyManager().take(seller.getUniqueId(), payment);
                payment = trimmedAmount * current.getPriceEach();
                if (trimmedAmount <= 0 || !plugin.getCurrencyManager().give(seller.getUniqueId(), payment)) {
                    return FillResult.error(trimmedAmount <= 0 ? plugin.msg("order-not-found") : plugin.msg("no-currency-hook"), offered);
                }

                accepted = trimmedAccepted;
                rejected = trimmedRejected;
                acceptedAmount = trimmedAmount;
            }

            int previousFilled = current.getQuantityFilled();
            current.setQuantityFilled(previousFilled + acceptedAmount);

            boolean removedFulfilled = false;
            if (current.isFulfilled()) {
                orders.remove(orderId);
                removedFulfilled = true;
            }

            List<ItemStack> buyerPending = pendingDeliveries.computeIfAbsent(current.getBuyerUuid(), k -> new ArrayList<>());
            buyerPending.addAll(cloneItems(accepted));

            if (!save()) {
                removeLastAdded(buyerPending, accepted.size());
                if (buyerPending.isEmpty()) pendingDeliveries.remove(current.getBuyerUuid());

                current.setQuantityFilled(previousFilled);
                if (removedFulfilled) orders.put(orderId, current);

                boolean refunded = plugin.getCurrencyManager().take(seller.getUniqueId(), payment);
                save();
                return FillResult.error(plugin.msg(refunded ? "order-save-failed" : "refund-failed"), offered);
            }
        }

        seller.sendMessage(plugin.msg("order-filled",
                "{amount}", String.valueOf(acceptedAmount),
                "{material}", itemName(order.getItemTemplate()),
                "{payment}", plugin.getCurrencyManager().format(payment)));

        return FillResult.success(rejected);
    }

    private int splitAcceptedItems(List<ItemStack> source, ItemStack template, int maxAmount,
                                   List<ItemStack> accepted, List<ItemStack> rejected) {
        int remaining = Math.max(0, maxAmount);
        int acceptedAmount = 0;

        for (ItemStack item : source) {
            if (item == null || item.getType().isAir()) continue;

            if (!ItemMatcher.matchesCustomItem(item, template) || remaining <= 0) {
                rejected.add(item.clone());
                continue;
            }

            int take = Math.min(item.getAmount(), remaining);
            ItemStack acceptedCopy = item.clone();
            acceptedCopy.setAmount(take);
            accepted.add(acceptedCopy);
            acceptedAmount += take;
            remaining -= take;

            int leftover = item.getAmount() - take;
            if (leftover > 0) {
                ItemStack rejectedCopy = item.clone();
                rejectedCopy.setAmount(leftover);
                rejected.add(rejectedCopy);
            }
        }

        return acceptedAmount;
    }

    private List<ItemStack> cloneItems(List<ItemStack> items) {
        if (items == null || items.isEmpty()) return List.of();
        List<ItemStack> clones = new ArrayList<>();
        for (ItemStack item : items) {
            if (item == null || item.getType().isAir()) continue;
            clones.add(item.clone());
        }
        return clones;
    }

    private int countItems(Player player, ItemStack template) {
        int count = 0;

        for (ItemStack item : player.getInventory().getContents()) {
            if (item != null && ItemMatcher.matchesCustomItem(item, template)) {
                count += item.getAmount();
            }
        }

        return count;
    }

    public synchronized void addPending(UUID uuid, List<ItemStack> items) {
        pendingDeliveries.computeIfAbsent(uuid, k -> new ArrayList<>()).addAll(items);
        save();
    }

    private void removeLastAdded(List<ItemStack> items, int amount) {
        for (int i = 0; i < amount && !items.isEmpty(); i++) {
            items.remove(items.size() - 1);
        }
    }

    public synchronized List<ItemStack> getPending(UUID uuid) {
        return new ArrayList<>(pendingDeliveries.getOrDefault(uuid, Collections.emptyList()));
    }

    public synchronized List<ItemStack> getPendingDeliveries(UUID uuid) {
        return getPending(uuid);
    }

    public synchronized void clearPending(UUID uuid) {
        pendingDeliveries.remove(uuid);
        save();
    }

    public synchronized void clearPendingDeliveries(UUID uuid) {
        clearPending(uuid);
    }

    private List<ItemStack> loadPendingItems(YamlConfiguration config, String path) {
        List<?> legacy = config.getList(path);
        if (legacy != null) {
            List<ItemStack> items = new ArrayList<>();
            for (Object o : legacy) {
                if (o instanceof ItemStack item) items.add(item);
            }
            return items;
        }

        if (!config.isConfigurationSection(path)) return Collections.emptyList();

        List<ItemStack> items = new ArrayList<>();
        for (String key : config.getConfigurationSection(path).getKeys(false)) {
            try {
                String itemPath = path + "." + key + ".";
                ItemStack item = config.getItemStack(itemPath + "item-stack");
                if (item == null) {
                    Material material = Material.valueOf(config.getString(itemPath + "item-data.material"));
                    item = new ItemStack(material);
                }

                restoreItem(config, itemPath + "item-data.", item);
                item.setAmount(Math.max(1, config.getInt(itemPath + "amount", item.getAmount())));
                items.add(item);
            } catch (Exception ex) {
                plugin.getLogger().log(Level.WARNING, "Failed to load pending item " + path + "." + key, ex);
            }
        }
        return items;
    }

    private void restoreItem(YamlConfiguration config, String path, ItemStack item) {
        ItemMeta meta = item.getItemMeta();
        if (meta == null) return;

        String name = config.getString(path + "name");
        if (name != null) meta.setDisplayName(name);

        List<String> lore = config.getStringList(path + "lore");
        if (!lore.isEmpty()) meta.setLore(lore);

        if (config.isSet(path + "custom-model-data")) {
            meta.setCustomModelData(config.getInt(path + "custom-model-data"));
        }

        if (config.isConfigurationSection(path + "enchantments")) {
            for (String k : config.getConfigurationSection(path + "enchantments").getKeys(false)) {
                NamespacedKey key = NamespacedKey.fromString(k);
                Enchantment ench = key != null ? Enchantment.getByKey(key) : null;
                if (ench != null) {
                    meta.addEnchant(ench, config.getInt(path + "enchantments." + k), true);
                }
            }
        }

        if (config.isConfigurationSection(path + "pdc")) {
            PersistentDataContainer pdc = meta.getPersistentDataContainer();

            for (String k : config.getConfigurationSection(path + "pdc").getKeys(false)) {
                NamespacedKey key = NamespacedKey.fromString(k);
                if (key == null) continue;

                Object val = config.get(path + "pdc." + k);
                writePdc(pdc, key, val);
            }
        }

        item.setItemMeta(meta);
    }

    private void writePdc(PersistentDataContainer pdc, NamespacedKey key, Object val) {
        if (val instanceof String s) pdc.set(key, PersistentDataType.STRING, s);
        else if (val instanceof Integer i) pdc.set(key, PersistentDataType.INTEGER, i);
        else if (val instanceof Long l) pdc.set(key, PersistentDataType.LONG, l);
        else if (val instanceof Double d) pdc.set(key, PersistentDataType.DOUBLE, d);
    }

    public static String itemName(ItemStack item) {
        if (item == null) return "Unknown";
        ItemMeta meta = item.getItemMeta();
        if (meta != null && meta.hasDisplayName()) return meta.getDisplayName();
        return item.getType().name().toLowerCase().replace("_", " ");
    }

    public static Material parseMaterial(String input) {
        if (input == null || input.isBlank()) return null;
        return Material.matchMaterial(input.trim());
    }

    public static String materialName(Material material) {
        if (material == null) return "unknown";
        return material.name().toLowerCase().replace("_", " ");
    }
}
